locale: es-MX
title: "Laboratorio de Neurocognición Social"
description: "Neurocognición Social"
theme: jekyll-theme-cayman

navigation:
 - title: Inicio
   url: /index.html
 - title: Contacto
   url: /contacto
- title: Proyectos
   url: /proyectos
