locale: es-MX
title: "Laboratorio de Neurocognición Social"
description: "Neurocognición Social"
theme: jekyll-theme-cayman
google_analytics: UA-135918948-1

navigation:
- title: 
  url: /index
- title: Miembros
  url: /miembros
- title: Proyectos
  url: /proyectos
- title: Publicaciones
  url: /publicaciones
- title: Colaboraciones
  url: /colaboraciones
- title: Contacto
  url: /contacto
- title: Eventos
  url: /eventos
  
